/*
 * Document AI API
 *
 * Use next-generation AI to extract data, fields, insights and text from documents. Instantly.
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Cloudmersive.APIClient.NET.DocumentAI.Client.FileParameter;
using OpenAPIDateConverter = Cloudmersive.APIClient.NET.DocumentAI.Client.OpenAPIDateConverter;

namespace Cloudmersive.APIClient.NET.DocumentAI.Model
{
    /// <summary>
    /// Document category option
    /// </summary>
    [DataContract(Name = "DocumentCategories")]
    public partial class DocumentCategories : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="DocumentCategories" /> class.
        /// </summary>
        /// <param name="categoryName">Name of the classification.</param>
        /// <param name="categoryDescription">Optional but recommended: Description of the classification in natural langugage.</param>
        public DocumentCategories(string categoryName = default, string categoryDescription = default)
        {
            this.CategoryName = categoryName;
            this.CategoryDescription = categoryDescription;
        }

        /// <summary>
        /// Name of the classification
        /// </summary>
        /// <value>Name of the classification</value>
        [DataMember(Name = "CategoryName", EmitDefaultValue = false)]
        public string CategoryName { get; set; }

        /// <summary>
        /// Optional but recommended: Description of the classification in natural langugage
        /// </summary>
        /// <value>Optional but recommended: Description of the classification in natural langugage</value>
        [DataMember(Name = "CategoryDescription", EmitDefaultValue = false)]
        public string CategoryDescription { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class DocumentCategories {\n");
            sb.Append("  CategoryName: ").Append(CategoryName).Append("\n");
            sb.Append("  CategoryDescription: ").Append(CategoryDescription).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
