/*
 * Document AI API
 *
 * Use next-generation AI to extract data, fields, insights and text from documents. Instantly.
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Cloudmersive.APIClient.NET.DocumentAI.Client.FileParameter;
using OpenAPIDateConverter = Cloudmersive.APIClient.NET.DocumentAI.Client.OpenAPIDateConverter;

namespace Cloudmersive.APIClient.NET.DocumentAI.Model
{
    /// <summary>
    /// Table extracted from a document
    /// </summary>
    [DataContract(Name = "TableResult")]
    public partial class TableResult : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="TableResult" /> class.
        /// </summary>
        /// <param name="title">Title of the table (optional).</param>
        /// <param name="rows">Rows of the table.</param>
        public TableResult(string title = default, List<TableResultRow> rows = default)
        {
            this.Title = title;
            this.Rows = rows;
        }

        /// <summary>
        /// Title of the table (optional)
        /// </summary>
        /// <value>Title of the table (optional)</value>
        [DataMember(Name = "Title", EmitDefaultValue = false)]
        public string Title { get; set; }

        /// <summary>
        /// Rows of the table
        /// </summary>
        /// <value>Rows of the table</value>
        [DataMember(Name = "Rows", EmitDefaultValue = false)]
        public List<TableResultRow> Rows { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class TableResult {\n");
            sb.Append("  Title: ").Append(Title).Append("\n");
            sb.Append("  Rows: ").Append(Rows).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
