/*
 * Document AI API
 *
 * Use next-generation AI to extract data, fields, insights and text from documents. Instantly.
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using Xunit;

using Cloudmersive.APIClient.NET.DocumentAI.Client;
using Cloudmersive.APIClient.NET.DocumentAI.Api;
// uncomment below to import models
//using Cloudmersive.APIClient.NET.DocumentAI.Model;

namespace Cloudmersive.APIClient.NET.DocumentAI.Test.Api
{
    /// <summary>
    ///  Class for testing AnalyzeApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class AnalyzeApiTests : IDisposable
    {
        private AnalyzeApi instance;

        public AnalyzeApiTests()
        {
            instance = new AnalyzeApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of AnalyzeApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' AnalyzeApi
            //Assert.IsType<AnalyzeApi>(instance);
        }

        /// <summary>
        /// Test ApplyRules
        /// </summary>
        [Fact]
        public void ApplyRulesTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //DocumentPolicyRequest body = null;
            //var response = instance.ApplyRules(body);
            //Assert.IsType<DocumentPolicyResult>(response);
        }
    }
}
