/* 
 * Document AI API
 *
 * Use next-generation AI to extract data, fields, insights and text from documents. Instantly.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using Cloudmersive.APIClient.NET.DocumentAI.Client;
using Cloudmersive.APIClient.NET.DocumentAI.Api;
using Cloudmersive.APIClient.NET.DocumentAI.Model;

namespace Cloudmersive.APIClient.NET.DocumentAI.Test
{
    /// <summary>
    ///  Class for testing AnalyzeApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class AnalyzeApiTests
    {
        private AnalyzeApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new AnalyzeApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of AnalyzeApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' AnalyzeApi
            //Assert.IsInstanceOfType(typeof(AnalyzeApi), instance, "instance is a AnalyzeApi");
        }

        
        /// <summary>
        /// Test ApplyRules
        /// </summary>
        [Test]
        public void ApplyRulesTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //DocumentPolicyRequest body = null;
            //var response = instance.ApplyRules(body);
            //Assert.IsInstanceOf<DocumentPolicyResult> (response, "response is DocumentPolicyResult");
        }
        
    }

}
