/* 
 * Document AI API
 *
 * Use next-generation AI to extract data, fields, insights and text from documents. Instantly.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using Cloudmersive.APIClient.NET.DocumentAI.Client;
using Cloudmersive.APIClient.NET.DocumentAI.Api;
using Cloudmersive.APIClient.NET.DocumentAI.Model;

namespace Cloudmersive.APIClient.NET.DocumentAI.Test
{
    /// <summary>
    ///  Class for testing ExtractApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class ExtractApiTests
    {
        private ExtractApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new ExtractApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ExtractApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' ExtractApi
            //Assert.IsInstanceOfType(typeof(ExtractApi), instance, "instance is a ExtractApi");
        }

        
        /// <summary>
        /// Test ExtractAllFieldsAndTables
        /// </summary>
        [Test]
        public void ExtractAllFieldsAndTablesTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string recognitionMode = null;
            //System.IO.Stream inputFile = null;
            //var response = instance.ExtractAllFieldsAndTables(recognitionMode, inputFile);
            //Assert.IsInstanceOf<ExtractFieldsAndTablesResponse> (response, "response is ExtractFieldsAndTablesResponse");
        }
        
        /// <summary>
        /// Test ExtractBarcodes
        /// </summary>
        [Test]
        public void ExtractBarcodesTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string recognitionMode = null;
            //System.IO.Stream inputFile = null;
            //var response = instance.ExtractBarcodes(recognitionMode, inputFile);
            //Assert.IsInstanceOf<ExtractBarcodesAiResponse> (response, "response is ExtractBarcodesAiResponse");
        }
        
        /// <summary>
        /// Test ExtractClassification
        /// </summary>
        [Test]
        public void ExtractClassificationTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string categories = null;
            //string recognitionMode = null;
            //System.IO.Stream inputFile = null;
            //var response = instance.ExtractClassification(categories, recognitionMode, inputFile);
            //Assert.IsInstanceOf<DocumentClassificationResult> (response, "response is DocumentClassificationResult");
        }
        
        /// <summary>
        /// Test ExtractClassificationAdvanced
        /// </summary>
        [Test]
        public void ExtractClassificationAdvancedTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string recognitionMode = null;
            //AdvancedExtractClassificationRequest body = null;
            //var response = instance.ExtractClassificationAdvanced(recognitionMode, body);
            //Assert.IsInstanceOf<DocumentAdvancedClassificationResult> (response, "response is DocumentAdvancedClassificationResult");
        }
        
        /// <summary>
        /// Test ExtractFields
        /// </summary>
        [Test]
        public void ExtractFieldsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string fieldNames = null;
            //string recognitionMode = null;
            //System.IO.Stream inputFile = null;
            //var response = instance.ExtractFields(fieldNames, recognitionMode, inputFile);
            //Assert.IsInstanceOf<ExtractFieldsResponse> (response, "response is ExtractFieldsResponse");
        }
        
        /// <summary>
        /// Test ExtractFieldsAdvanced
        /// </summary>
        [Test]
        public void ExtractFieldsAdvancedTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string recognitionMode = null;
            //AdvancedExtractFieldsRequest body = null;
            //var response = instance.ExtractFieldsAdvanced(recognitionMode, body);
            //Assert.IsInstanceOf<ExtractFieldsResponse> (response, "response is ExtractFieldsResponse");
        }
        
        /// <summary>
        /// Test ExtractSummary
        /// </summary>
        [Test]
        public void ExtractSummaryTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string recognitionMode = null;
            //System.IO.Stream inputFile = null;
            //var response = instance.ExtractSummary(recognitionMode, inputFile);
            //Assert.IsInstanceOf<SummarizeDocumentResponse> (response, "response is SummarizeDocumentResponse");
        }
        
        /// <summary>
        /// Test ExtractTables
        /// </summary>
        [Test]
        public void ExtractTablesTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string recognitionMode = null;
            //System.IO.Stream inputFile = null;
            //var response = instance.ExtractTables(recognitionMode, inputFile);
            //Assert.IsInstanceOf<ExtractTablesResponse> (response, "response is ExtractTablesResponse");
        }
        
        /// <summary>
        /// Test ExtractText
        /// </summary>
        [Test]
        public void ExtractTextTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string recognitionMode = null;
            //System.IO.Stream inputFile = null;
            //var response = instance.ExtractText(recognitionMode, inputFile);
            //Assert.IsInstanceOf<ExtractTextResponse> (response, "response is ExtractTextResponse");
        }
        
    }

}
