/* 
 * Document AI API
 *
 * Use next-generation AI to extract data, fields, insights and text from documents. Instantly.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using Cloudmersive.APIClient.NET.DocumentAI.Client;
using Cloudmersive.APIClient.NET.DocumentAI.Api;
using Cloudmersive.APIClient.NET.DocumentAI.Model;

namespace Cloudmersive.APIClient.NET.DocumentAI.Test
{
    /// <summary>
    ///  Class for testing RunBatchJobApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class RunBatchJobApiTests
    {
        private RunBatchJobApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new RunBatchJobApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of RunBatchJobApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' RunBatchJobApi
            //Assert.IsInstanceOfType(typeof(RunBatchJobApi), instance, "instance is a RunBatchJobApi");
        }

        
        /// <summary>
        /// Test ExtractAllFieldsAndTablesFromDocumentBatchJob
        /// </summary>
        [Test]
        public void ExtractAllFieldsAndTablesFromDocumentBatchJobTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string recognitionMode = null;
            //System.IO.Stream inputFile = null;
            //var response = instance.ExtractAllFieldsAndTablesFromDocumentBatchJob(recognitionMode, inputFile);
            //Assert.IsInstanceOf<ExtractDocumentBatchJobResult> (response, "response is ExtractDocumentBatchJobResult");
        }
        
        /// <summary>
        /// Test ExtractClassificationFromDocumentBatchJob
        /// </summary>
        [Test]
        public void ExtractClassificationFromDocumentBatchJobTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string categories = null;
            //string recognitionMode = null;
            //System.IO.Stream inputFile = null;
            //var response = instance.ExtractClassificationFromDocumentBatchJob(categories, recognitionMode, inputFile);
            //Assert.IsInstanceOf<ExtractDocumentBatchJobResult> (response, "response is ExtractDocumentBatchJobResult");
        }
        
        /// <summary>
        /// Test ExtractFieldsFromDocumentAdvancedBatchJob
        /// </summary>
        [Test]
        public void ExtractFieldsFromDocumentAdvancedBatchJobTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string recognitionMode = null;
            //AdvancedExtractFieldsRequest body = null;
            //var response = instance.ExtractFieldsFromDocumentAdvancedBatchJob(recognitionMode, body);
            //Assert.IsInstanceOf<ExtractDocumentBatchJobResult> (response, "response is ExtractDocumentBatchJobResult");
        }
        
        /// <summary>
        /// Test ExtractTextFromDocumentBatchJob
        /// </summary>
        [Test]
        public void ExtractTextFromDocumentBatchJobTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string recognitionMode = null;
            //System.IO.Stream inputFile = null;
            //var response = instance.ExtractTextFromDocumentBatchJob(recognitionMode, inputFile);
            //Assert.IsInstanceOf<ExtractDocumentBatchJobResult> (response, "response is ExtractDocumentBatchJobResult");
        }
        
        /// <summary>
        /// Test GetAsyncJobStatus
        /// </summary>
        [Test]
        public void GetAsyncJobStatusTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string asyncJobID = null;
            //var response = instance.GetAsyncJobStatus(asyncJobID);
            //Assert.IsInstanceOf<ExtractDocumentJobStatusResult> (response, "response is ExtractDocumentJobStatusResult");
        }
        
    }

}
