/*
 * Document AI API
 *
 * Use next-generation AI to extract data, fields, insights and text from documents. Instantly.
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using Xunit;

using Cloudmersive.APIClient.NET.DocumentAI.Client;
using Cloudmersive.APIClient.NET.DocumentAI.Api;
// uncomment below to import models
//using Cloudmersive.APIClient.NET.DocumentAI.Model;

namespace Cloudmersive.APIClient.NET.DocumentAI.Test.Api
{
    /// <summary>
    ///  Class for testing RunBatchJobApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class RunBatchJobApiTests : IDisposable
    {
        private RunBatchJobApi instance;

        public RunBatchJobApiTests()
        {
            instance = new RunBatchJobApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of RunBatchJobApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' RunBatchJobApi
            //Assert.IsType<RunBatchJobApi>(instance);
        }

        /// <summary>
        /// Test ExtractAllFieldsAndTablesFromDocumentBatchJob
        /// </summary>
        [Fact]
        public void ExtractAllFieldsAndTablesFromDocumentBatchJobTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string recognitionMode = null;
            //FileParameter inputFile = null;
            //var response = instance.ExtractAllFieldsAndTablesFromDocumentBatchJob(recognitionMode, inputFile);
            //Assert.IsType<ExtractDocumentBatchJobResult>(response);
        }

        /// <summary>
        /// Test ExtractClassificationFromDocumentBatchJob
        /// </summary>
        [Fact]
        public void ExtractClassificationFromDocumentBatchJobTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string categories = null;
            //string recognitionMode = null;
            //FileParameter inputFile = null;
            //var response = instance.ExtractClassificationFromDocumentBatchJob(categories, recognitionMode, inputFile);
            //Assert.IsType<ExtractDocumentBatchJobResult>(response);
        }

        /// <summary>
        /// Test ExtractFieldsFromDocumentAdvancedBatchJob
        /// </summary>
        [Fact]
        public void ExtractFieldsFromDocumentAdvancedBatchJobTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string recognitionMode = null;
            //AdvancedExtractFieldsRequest body = null;
            //var response = instance.ExtractFieldsFromDocumentAdvancedBatchJob(recognitionMode, body);
            //Assert.IsType<ExtractDocumentBatchJobResult>(response);
        }

        /// <summary>
        /// Test ExtractTextFromDocumentBatchJob
        /// </summary>
        [Fact]
        public void ExtractTextFromDocumentBatchJobTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string recognitionMode = null;
            //FileParameter inputFile = null;
            //var response = instance.ExtractTextFromDocumentBatchJob(recognitionMode, inputFile);
            //Assert.IsType<ExtractDocumentBatchJobResult>(response);
        }

        /// <summary>
        /// Test GetAsyncJobStatus
        /// </summary>
        [Fact]
        public void GetAsyncJobStatusTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string asyncJobID = null;
            //var response = instance.GetAsyncJobStatus(asyncJobID);
            //Assert.IsType<ExtractDocumentJobStatusResult>(response);
        }
    }
}
