/* 
 * Document AI API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using Cloudmersive.APIClient.NET.DocumentAI.Client;
using Cloudmersive.APIClient.NET.DocumentAI.Api;
using Cloudmersive.APIClient.NET.DocumentAI.Model;

namespace Cloudmersive.APIClient.NET.DocumentAI.Test
{
    /// <summary>
    ///  Class for testing RunBatchJobApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class RunBatchJobApiTests
    {
        private RunBatchJobApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new RunBatchJobApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of RunBatchJobApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' RunBatchJobApi
            //Assert.IsInstanceOfType(typeof(RunBatchJobApi), instance, "instance is a RunBatchJobApi");
        }

        
        /// <summary>
        /// Test DocumentAiDocumentBatchJobBatchJobStatusGet
        /// </summary>
        [Test]
        public void DocumentAiDocumentBatchJobBatchJobStatusGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string asyncJobID = null;
            //var response = instance.DocumentAiDocumentBatchJobBatchJobStatusGet(asyncJobID);
            //Assert.IsInstanceOf<ExtractDocumentJobStatusResult> (response, "response is ExtractDocumentJobStatusResult");
        }
        
        /// <summary>
        /// Test DocumentAiDocumentBatchJobExtractAllPost
        /// </summary>
        [Test]
        public void DocumentAiDocumentBatchJobExtractAllPostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string recognitionMode = null;
            //System.IO.Stream inputFile = null;
            //var response = instance.DocumentAiDocumentBatchJobExtractAllPost(recognitionMode, inputFile);
            //Assert.IsInstanceOf<ExtractDocumentBatchJobResult> (response, "response is ExtractDocumentBatchJobResult");
        }
        
        /// <summary>
        /// Test DocumentAiDocumentBatchJobExtractClassifyPost
        /// </summary>
        [Test]
        public void DocumentAiDocumentBatchJobExtractClassifyPostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string categories = null;
            //string recognitionMode = null;
            //System.IO.Stream inputFile = null;
            //var response = instance.DocumentAiDocumentBatchJobExtractClassifyPost(categories, recognitionMode, inputFile);
            //Assert.IsInstanceOf<ExtractDocumentBatchJobResult> (response, "response is ExtractDocumentBatchJobResult");
        }
        
        /// <summary>
        /// Test DocumentAiDocumentBatchJobExtractFieldsAdvancedPost
        /// </summary>
        [Test]
        public void DocumentAiDocumentBatchJobExtractFieldsAdvancedPostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string recognitionMode = null;
            //AdvancedExtractFieldsRequest body = null;
            //var response = instance.DocumentAiDocumentBatchJobExtractFieldsAdvancedPost(recognitionMode, body);
            //Assert.IsInstanceOf<ExtractDocumentBatchJobResult> (response, "response is ExtractDocumentBatchJobResult");
        }
        
        /// <summary>
        /// Test DocumentAiDocumentBatchJobExtractTextPost
        /// </summary>
        [Test]
        public void DocumentAiDocumentBatchJobExtractTextPostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string recognitionMode = null;
            //System.IO.Stream inputFile = null;
            //var response = instance.DocumentAiDocumentBatchJobExtractTextPost(recognitionMode, inputFile);
            //Assert.IsInstanceOf<ExtractDocumentBatchJobResult> (response, "response is ExtractDocumentBatchJobResult");
        }
        
    }

}
