/* 
 * Document AI API
 *
 * Use next-generation AI to extract data, fields, insights and text from documents. Instantly.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Cloudmersive.APIClient.NET.DocumentAI.Api;
using Cloudmersive.APIClient.NET.DocumentAI.Model;
using Cloudmersive.APIClient.NET.DocumentAI.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Cloudmersive.APIClient.NET.DocumentAI.Test
{
    /// <summary>
    ///  Class for testing AdvancedExtractFieldsRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class AdvancedExtractFieldsRequestTests
    {
        // TODO uncomment below to declare an instance variable for AdvancedExtractFieldsRequest
        //private AdvancedExtractFieldsRequest instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of AdvancedExtractFieldsRequest
            //instance = new AdvancedExtractFieldsRequest();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of AdvancedExtractFieldsRequest
        /// </summary>
        [Test]
        public void AdvancedExtractFieldsRequestInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" AdvancedExtractFieldsRequest
            //Assert.IsInstanceOfType<AdvancedExtractFieldsRequest> (instance, "variable 'instance' is a AdvancedExtractFieldsRequest");
        }


        /// <summary>
        /// Test the property 'InputFile'
        /// </summary>
        [Test]
        public void InputFileTest()
        {
            // TODO unit test for the property 'InputFile'
        }
        /// <summary>
        /// Test the property 'FieldsToExtract'
        /// </summary>
        [Test]
        public void FieldsToExtractTest()
        {
            // TODO unit test for the property 'FieldsToExtract'
        }
        /// <summary>
        /// Test the property 'MaximumPagesProcessed'
        /// </summary>
        [Test]
        public void MaximumPagesProcessedTest()
        {
            // TODO unit test for the property 'MaximumPagesProcessed'
        }
        /// <summary>
        /// Test the property 'Preprocessing'
        /// </summary>
        [Test]
        public void PreprocessingTest()
        {
            // TODO unit test for the property 'Preprocessing'
        }
        /// <summary>
        /// Test the property 'ResultCrossCheck'
        /// </summary>
        [Test]
        public void ResultCrossCheckTest()
        {
            // TODO unit test for the property 'ResultCrossCheck'
        }

    }

}
