/* 
 * Document AI API
 *
 * Use next-generation AI to extract data, fields, insights and text from documents. Instantly.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Cloudmersive.APIClient.NET.DocumentAI.Api;
using Cloudmersive.APIClient.NET.DocumentAI.Model;
using Cloudmersive.APIClient.NET.DocumentAI.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Cloudmersive.APIClient.NET.DocumentAI.Test
{
    /// <summary>
    ///  Class for testing AdvancedExtractClassificationRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class AdvancedExtractClassificationRequestTests
    {
        // TODO uncomment below to declare an instance variable for AdvancedExtractClassificationRequest
        //private AdvancedExtractClassificationRequest instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of AdvancedExtractClassificationRequest
            //instance = new AdvancedExtractClassificationRequest();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of AdvancedExtractClassificationRequest
        /// </summary>
        [Test]
        public void AdvancedExtractClassificationRequestInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" AdvancedExtractClassificationRequest
            //Assert.IsInstanceOfType<AdvancedExtractClassificationRequest> (instance, "variable 'instance' is a AdvancedExtractClassificationRequest");
        }


        /// <summary>
        /// Test the property 'InputFile'
        /// </summary>
        [Test]
        public void InputFileTest()
        {
            // TODO unit test for the property 'InputFile'
        }
        /// <summary>
        /// Test the property 'Categories'
        /// </summary>
        [Test]
        public void CategoriesTest()
        {
            // TODO unit test for the property 'Categories'
        }
        /// <summary>
        /// Test the property 'MaximumPagesProcessed'
        /// </summary>
        [Test]
        public void MaximumPagesProcessedTest()
        {
            // TODO unit test for the property 'MaximumPagesProcessed'
        }

    }

}
