/*
 * Document AI API
 *
 * Use next-generation AI to extract data, fields, insights and text from documents. Instantly.
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Cloudmersive.APIClient.NET.DocumentAI.Model;
using Cloudmersive.APIClient.NET.DocumentAI.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Cloudmersive.APIClient.NET.DocumentAI.Test.Model
{
    /// <summary>
    ///  Class for testing AdvancedExtractFieldsRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class AdvancedExtractFieldsRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for AdvancedExtractFieldsRequest
        //private AdvancedExtractFieldsRequest instance;

        public AdvancedExtractFieldsRequestTests()
        {
            // TODO uncomment below to create an instance of AdvancedExtractFieldsRequest
            //instance = new AdvancedExtractFieldsRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of AdvancedExtractFieldsRequest
        /// </summary>
        [Fact]
        public void AdvancedExtractFieldsRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" AdvancedExtractFieldsRequest
            //Assert.IsType<AdvancedExtractFieldsRequest>(instance);
        }

        /// <summary>
        /// Test the property 'InputFile'
        /// </summary>
        [Fact]
        public void InputFileTest()
        {
            // TODO unit test for the property 'InputFile'
        }

        /// <summary>
        /// Test the property 'FieldsToExtract'
        /// </summary>
        [Fact]
        public void FieldsToExtractTest()
        {
            // TODO unit test for the property 'FieldsToExtract'
        }

        /// <summary>
        /// Test the property 'MaximumPagesProcessed'
        /// </summary>
        [Fact]
        public void MaximumPagesProcessedTest()
        {
            // TODO unit test for the property 'MaximumPagesProcessed'
        }

        /// <summary>
        /// Test the property 'Preprocessing'
        /// </summary>
        [Fact]
        public void PreprocessingTest()
        {
            // TODO unit test for the property 'Preprocessing'
        }

        /// <summary>
        /// Test the property 'ResultCrossCheck'
        /// </summary>
        [Fact]
        public void ResultCrossCheckTest()
        {
            // TODO unit test for the property 'ResultCrossCheck'
        }

        /// <summary>
        /// Test the property 'RotateImageDegrees'
        /// </summary>
        [Fact]
        public void RotateImageDegreesTest()
        {
            // TODO unit test for the property 'RotateImageDegrees'
        }
    }
}
