/* 
 * Document AI API
 *
 * Use next-generation AI to extract data, fields, insights and text from documents. Instantly.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Cloudmersive.APIClient.NET.DocumentAI.Api;
using Cloudmersive.APIClient.NET.DocumentAI.Model;
using Cloudmersive.APIClient.NET.DocumentAI.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Cloudmersive.APIClient.NET.DocumentAI.Test
{
    /// <summary>
    ///  Class for testing DocumentQuestionBoolean
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class DocumentQuestionBooleanTests
    {
        // TODO uncomment below to declare an instance variable for DocumentQuestionBoolean
        //private DocumentQuestionBoolean instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of DocumentQuestionBoolean
            //instance = new DocumentQuestionBoolean();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of DocumentQuestionBoolean
        /// </summary>
        [Test]
        public void DocumentQuestionBooleanInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" DocumentQuestionBoolean
            //Assert.IsInstanceOfType<DocumentQuestionBoolean> (instance, "variable 'instance' is a DocumentQuestionBoolean");
        }


        /// <summary>
        /// Test the property 'QuestionId'
        /// </summary>
        [Test]
        public void QuestionIdTest()
        {
            // TODO unit test for the property 'QuestionId'
        }
        /// <summary>
        /// Test the property 'QuestionText'
        /// </summary>
        [Test]
        public void QuestionTextTest()
        {
            // TODO unit test for the property 'QuestionText'
        }

    }

}
