/* 
 * Document AI API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Cloudmersive.APIClient.NET.DocumentAI.Api;
using Cloudmersive.APIClient.NET.DocumentAI.Model;
using Cloudmersive.APIClient.NET.DocumentAI.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Cloudmersive.APIClient.NET.DocumentAI.Test
{
    /// <summary>
    ///  Class for testing DocumentPolicyResult
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class DocumentPolicyResultTests
    {
        // TODO uncomment below to declare an instance variable for DocumentPolicyResult
        //private DocumentPolicyResult instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of DocumentPolicyResult
            //instance = new DocumentPolicyResult();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of DocumentPolicyResult
        /// </summary>
        [Test]
        public void DocumentPolicyResultInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" DocumentPolicyResult
            //Assert.IsInstanceOfType<DocumentPolicyResult> (instance, "variable 'instance' is a DocumentPolicyResult");
        }


        /// <summary>
        /// Test the property 'CleanResult'
        /// </summary>
        [Test]
        public void CleanResultTest()
        {
            // TODO unit test for the property 'CleanResult'
        }
        /// <summary>
        /// Test the property 'RiskScore'
        /// </summary>
        [Test]
        public void RiskScoreTest()
        {
            // TODO unit test for the property 'RiskScore'
        }
        /// <summary>
        /// Test the property 'RuleViolations'
        /// </summary>
        [Test]
        public void RuleViolationsTest()
        {
            // TODO unit test for the property 'RuleViolations'
        }

    }

}
