/* 
 * Document AI API
 *
 * Use next-generation AI to extract data, fields, insights and text from documents. Instantly.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Cloudmersive.APIClient.NET.DocumentAI.Api;
using Cloudmersive.APIClient.NET.DocumentAI.Model;
using Cloudmersive.APIClient.NET.DocumentAI.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Cloudmersive.APIClient.NET.DocumentAI.Test
{
    /// <summary>
    ///  Class for testing DocumentQuestionFreeResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class DocumentQuestionFreeResponseTests
    {
        // TODO uncomment below to declare an instance variable for DocumentQuestionFreeResponse
        //private DocumentQuestionFreeResponse instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of DocumentQuestionFreeResponse
            //instance = new DocumentQuestionFreeResponse();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of DocumentQuestionFreeResponse
        /// </summary>
        [Test]
        public void DocumentQuestionFreeResponseInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" DocumentQuestionFreeResponse
            //Assert.IsInstanceOfType<DocumentQuestionFreeResponse> (instance, "variable 'instance' is a DocumentQuestionFreeResponse");
        }


        /// <summary>
        /// Test the property 'QuestionId'
        /// </summary>
        [Test]
        public void QuestionIdTest()
        {
            // TODO unit test for the property 'QuestionId'
        }
        /// <summary>
        /// Test the property 'QuestionText'
        /// </summary>
        [Test]
        public void QuestionTextTest()
        {
            // TODO unit test for the property 'QuestionText'
        }

    }

}
