/* 
 * Document AI API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Cloudmersive.APIClient.NET.DocumentAI.Api;
using Cloudmersive.APIClient.NET.DocumentAI.Model;
using Cloudmersive.APIClient.NET.DocumentAI.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Cloudmersive.APIClient.NET.DocumentAI.Test
{
    /// <summary>
    ///  Class for testing DocumentPolicyRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class DocumentPolicyRequestTests
    {
        // TODO uncomment below to declare an instance variable for DocumentPolicyRequest
        //private DocumentPolicyRequest instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of DocumentPolicyRequest
            //instance = new DocumentPolicyRequest();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of DocumentPolicyRequest
        /// </summary>
        [Test]
        public void DocumentPolicyRequestInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" DocumentPolicyRequest
            //Assert.IsInstanceOfType<DocumentPolicyRequest> (instance, "variable 'instance' is a DocumentPolicyRequest");
        }


        /// <summary>
        /// Test the property 'InputFile'
        /// </summary>
        [Test]
        public void InputFileTest()
        {
            // TODO unit test for the property 'InputFile'
        }
        /// <summary>
        /// Test the property 'Rules'
        /// </summary>
        [Test]
        public void RulesTest()
        {
            // TODO unit test for the property 'Rules'
        }

    }

}
