/* 
 * Document AI API
 *
 * Use next-generation AI to extract data, fields, insights and text from documents. Instantly.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Cloudmersive.APIClient.NET.DocumentAI.Api;
using Cloudmersive.APIClient.NET.DocumentAI.Model;
using Cloudmersive.APIClient.NET.DocumentAI.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Cloudmersive.APIClient.NET.DocumentAI.Test
{
    /// <summary>
    ///  Class for testing DocumentQuestionsRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class DocumentQuestionsRequestTests
    {
        // TODO uncomment below to declare an instance variable for DocumentQuestionsRequest
        //private DocumentQuestionsRequest instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of DocumentQuestionsRequest
            //instance = new DocumentQuestionsRequest();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of DocumentQuestionsRequest
        /// </summary>
        [Test]
        public void DocumentQuestionsRequestInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" DocumentQuestionsRequest
            //Assert.IsInstanceOfType<DocumentQuestionsRequest> (instance, "variable 'instance' is a DocumentQuestionsRequest");
        }


        /// <summary>
        /// Test the property 'InputFile'
        /// </summary>
        [Test]
        public void InputFileTest()
        {
            // TODO unit test for the property 'InputFile'
        }
        /// <summary>
        /// Test the property 'QuestionsYesNo'
        /// </summary>
        [Test]
        public void QuestionsYesNoTest()
        {
            // TODO unit test for the property 'QuestionsYesNo'
        }
        /// <summary>
        /// Test the property 'QuestionsMultipleChoice'
        /// </summary>
        [Test]
        public void QuestionsMultipleChoiceTest()
        {
            // TODO unit test for the property 'QuestionsMultipleChoice'
        }
        /// <summary>
        /// Test the property 'QuestionsFreeResponse'
        /// </summary>
        [Test]
        public void QuestionsFreeResponseTest()
        {
            // TODO unit test for the property 'QuestionsFreeResponse'
        }
        /// <summary>
        /// Test the property 'RecognitionMode'
        /// </summary>
        [Test]
        public void RecognitionModeTest()
        {
            // TODO unit test for the property 'RecognitionMode'
        }

    }

}
