/* 
 * Document AI API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Cloudmersive.APIClient.NET.DocumentAI.Api;
using Cloudmersive.APIClient.NET.DocumentAI.Model;
using Cloudmersive.APIClient.NET.DocumentAI.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Cloudmersive.APIClient.NET.DocumentAI.Test
{
    /// <summary>
    ///  Class for testing DocumentClassificationResult
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class DocumentClassificationResultTests
    {
        // TODO uncomment below to declare an instance variable for DocumentClassificationResult
        //private DocumentClassificationResult instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of DocumentClassificationResult
            //instance = new DocumentClassificationResult();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of DocumentClassificationResult
        /// </summary>
        [Test]
        public void DocumentClassificationResultInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" DocumentClassificationResult
            //Assert.IsInstanceOfType<DocumentClassificationResult> (instance, "variable 'instance' is a DocumentClassificationResult");
        }


        /// <summary>
        /// Test the property 'Successful'
        /// </summary>
        [Test]
        public void SuccessfulTest()
        {
            // TODO unit test for the property 'Successful'
        }
        /// <summary>
        /// Test the property 'DocumentCategoryResult'
        /// </summary>
        [Test]
        public void DocumentCategoryResultTest()
        {
            // TODO unit test for the property 'DocumentCategoryResult'
        }

    }

}
