/*
 * Document AI API
 *
 * Use next-generation AI to extract data, fields, insights and text from documents. Instantly.
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Cloudmersive.APIClient.NET.DocumentAI.Model;
using Cloudmersive.APIClient.NET.DocumentAI.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Cloudmersive.APIClient.NET.DocumentAI.Test.Model
{
    /// <summary>
    ///  Class for testing DocumentPolicyResult
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class DocumentPolicyResultTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for DocumentPolicyResult
        //private DocumentPolicyResult instance;

        public DocumentPolicyResultTests()
        {
            // TODO uncomment below to create an instance of DocumentPolicyResult
            //instance = new DocumentPolicyResult();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of DocumentPolicyResult
        /// </summary>
        [Fact]
        public void DocumentPolicyResultInstanceTest()
        {
            // TODO uncomment below to test "IsType" DocumentPolicyResult
            //Assert.IsType<DocumentPolicyResult>(instance);
        }

        /// <summary>
        /// Test the property 'CleanResult'
        /// </summary>
        [Fact]
        public void CleanResultTest()
        {
            // TODO unit test for the property 'CleanResult'
        }

        /// <summary>
        /// Test the property 'RiskScore'
        /// </summary>
        [Fact]
        public void RiskScoreTest()
        {
            // TODO unit test for the property 'RiskScore'
        }

        /// <summary>
        /// Test the property 'RuleViolations'
        /// </summary>
        [Fact]
        public void RuleViolationsTest()
        {
            // TODO unit test for the property 'RuleViolations'
        }
    }
}
