/* 
 * Document AI API
 *
 * Use next-generation AI to extract data, fields, insights and text from documents. Instantly.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Cloudmersive.APIClient.NET.DocumentAI.Api;
using Cloudmersive.APIClient.NET.DocumentAI.Model;
using Cloudmersive.APIClient.NET.DocumentAI.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Cloudmersive.APIClient.NET.DocumentAI.Test
{
    /// <summary>
    ///  Class for testing DocumentQuestionAnswersResult
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class DocumentQuestionAnswersResultTests
    {
        // TODO uncomment below to declare an instance variable for DocumentQuestionAnswersResult
        //private DocumentQuestionAnswersResult instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of DocumentQuestionAnswersResult
            //instance = new DocumentQuestionAnswersResult();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of DocumentQuestionAnswersResult
        /// </summary>
        [Test]
        public void DocumentQuestionAnswersResultInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" DocumentQuestionAnswersResult
            //Assert.IsInstanceOfType<DocumentQuestionAnswersResult> (instance, "variable 'instance' is a DocumentQuestionAnswersResult");
        }


        /// <summary>
        /// Test the property 'Successful'
        /// </summary>
        [Test]
        public void SuccessfulTest()
        {
            // TODO unit test for the property 'Successful'
        }
        /// <summary>
        /// Test the property 'ConfidenceScore'
        /// </summary>
        [Test]
        public void ConfidenceScoreTest()
        {
            // TODO unit test for the property 'ConfidenceScore'
        }
        /// <summary>
        /// Test the property 'AnswerResults'
        /// </summary>
        [Test]
        public void AnswerResultsTest()
        {
            // TODO unit test for the property 'AnswerResults'
        }

    }

}
