/* 
 * Document AI API
 *
 * Use next-generation AI to extract data, fields, insights and text from documents. Instantly.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Cloudmersive.APIClient.NET.DocumentAI.Api;
using Cloudmersive.APIClient.NET.DocumentAI.Model;
using Cloudmersive.APIClient.NET.DocumentAI.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Cloudmersive.APIClient.NET.DocumentAI.Test
{
    /// <summary>
    ///  Class for testing DocumentQuestionChoiceItem
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class DocumentQuestionChoiceItemTests
    {
        // TODO uncomment below to declare an instance variable for DocumentQuestionChoiceItem
        //private DocumentQuestionChoiceItem instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of DocumentQuestionChoiceItem
            //instance = new DocumentQuestionChoiceItem();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of DocumentQuestionChoiceItem
        /// </summary>
        [Test]
        public void DocumentQuestionChoiceItemInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" DocumentQuestionChoiceItem
            //Assert.IsInstanceOfType<DocumentQuestionChoiceItem> (instance, "variable 'instance' is a DocumentQuestionChoiceItem");
        }


        /// <summary>
        /// Test the property 'ChoiceId'
        /// </summary>
        [Test]
        public void ChoiceIdTest()
        {
            // TODO unit test for the property 'ChoiceId'
        }
        /// <summary>
        /// Test the property 'ChoiceText'
        /// </summary>
        [Test]
        public void ChoiceTextTest()
        {
            // TODO unit test for the property 'ChoiceText'
        }

    }

}
