/*
 * Document AI API
 *
 * Use next-generation AI to extract data, fields, insights and text from documents. Instantly.
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Cloudmersive.APIClient.NET.DocumentAI.Model;
using Cloudmersive.APIClient.NET.DocumentAI.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Cloudmersive.APIClient.NET.DocumentAI.Test.Model
{
    /// <summary>
    ///  Class for testing DocumentCategories
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class DocumentCategoriesTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for DocumentCategories
        //private DocumentCategories instance;

        public DocumentCategoriesTests()
        {
            // TODO uncomment below to create an instance of DocumentCategories
            //instance = new DocumentCategories();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of DocumentCategories
        /// </summary>
        [Fact]
        public void DocumentCategoriesInstanceTest()
        {
            // TODO uncomment below to test "IsType" DocumentCategories
            //Assert.IsType<DocumentCategories>(instance);
        }

        /// <summary>
        /// Test the property 'CategoryName'
        /// </summary>
        [Fact]
        public void CategoryNameTest()
        {
            // TODO unit test for the property 'CategoryName'
        }

        /// <summary>
        /// Test the property 'CategoryDescription'
        /// </summary>
        [Fact]
        public void CategoryDescriptionTest()
        {
            // TODO unit test for the property 'CategoryDescription'
        }
    }
}
