/* 
 * Document AI API
 *
 * Use next-generation AI to extract data, fields, insights and text from documents. Instantly.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Cloudmersive.APIClient.NET.DocumentAI.Api;
using Cloudmersive.APIClient.NET.DocumentAI.Model;
using Cloudmersive.APIClient.NET.DocumentAI.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Cloudmersive.APIClient.NET.DocumentAI.Test
{
    /// <summary>
    ///  Class for testing DocumentQuestionAnswerItem
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class DocumentQuestionAnswerItemTests
    {
        // TODO uncomment below to declare an instance variable for DocumentQuestionAnswerItem
        //private DocumentQuestionAnswerItem instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of DocumentQuestionAnswerItem
            //instance = new DocumentQuestionAnswerItem();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of DocumentQuestionAnswerItem
        /// </summary>
        [Test]
        public void DocumentQuestionAnswerItemInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" DocumentQuestionAnswerItem
            //Assert.IsInstanceOfType<DocumentQuestionAnswerItem> (instance, "variable 'instance' is a DocumentQuestionAnswerItem");
        }


        /// <summary>
        /// Test the property 'QuestionId'
        /// </summary>
        [Test]
        public void QuestionIdTest()
        {
            // TODO unit test for the property 'QuestionId'
        }
        /// <summary>
        /// Test the property 'AnswerValue'
        /// </summary>
        [Test]
        public void AnswerValueTest()
        {
            // TODO unit test for the property 'AnswerValue'
        }
        /// <summary>
        /// Test the property 'AnswerRationale'
        /// </summary>
        [Test]
        public void AnswerRationaleTest()
        {
            // TODO unit test for the property 'AnswerRationale'
        }
        /// <summary>
        /// Test the property 'ConfidenceScore'
        /// </summary>
        [Test]
        public void ConfidenceScoreTest()
        {
            // TODO unit test for the property 'ConfidenceScore'
        }

    }

}
