/* 
 * Document AI API
 *
 * Use next-generation AI to extract data, fields, insights and text from documents. Instantly.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Cloudmersive.APIClient.NET.DocumentAI.Api;
using Cloudmersive.APIClient.NET.DocumentAI.Model;
using Cloudmersive.APIClient.NET.DocumentAI.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Cloudmersive.APIClient.NET.DocumentAI.Test
{
    /// <summary>
    ///  Class for testing ExtractedTextPage
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ExtractedTextPageTests
    {
        // TODO uncomment below to declare an instance variable for ExtractedTextPage
        //private ExtractedTextPage instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ExtractedTextPage
            //instance = new ExtractedTextPage();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ExtractedTextPage
        /// </summary>
        [Test]
        public void ExtractedTextPageInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ExtractedTextPage
            //Assert.IsInstanceOfType<ExtractedTextPage> (instance, "variable 'instance' is a ExtractedTextPage");
        }


        /// <summary>
        /// Test the property 'PageNumber'
        /// </summary>
        [Test]
        public void PageNumberTest()
        {
            // TODO unit test for the property 'PageNumber'
        }
        /// <summary>
        /// Test the property 'TextResult'
        /// </summary>
        [Test]
        public void TextResultTest()
        {
            // TODO unit test for the property 'TextResult'
        }

    }

}
