/*
 * Document AI API
 *
 * Use next-generation AI to extract data, fields, insights and text from documents. Instantly.
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Cloudmersive.APIClient.NET.DocumentAI.Model;
using Cloudmersive.APIClient.NET.DocumentAI.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Cloudmersive.APIClient.NET.DocumentAI.Test.Model
{
    /// <summary>
    ///  Class for testing ExtractedBarcodeItem
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ExtractedBarcodeItemTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ExtractedBarcodeItem
        //private ExtractedBarcodeItem instance;

        public ExtractedBarcodeItemTests()
        {
            // TODO uncomment below to create an instance of ExtractedBarcodeItem
            //instance = new ExtractedBarcodeItem();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ExtractedBarcodeItem
        /// </summary>
        [Fact]
        public void ExtractedBarcodeItemInstanceTest()
        {
            // TODO uncomment below to test "IsType" ExtractedBarcodeItem
            //Assert.IsType<ExtractedBarcodeItem>(instance);
        }

        /// <summary>
        /// Test the property 'BarcodeType'
        /// </summary>
        [Fact]
        public void BarcodeTypeTest()
        {
            // TODO unit test for the property 'BarcodeType'
        }

        /// <summary>
        /// Test the property 'BarcodeValue'
        /// </summary>
        [Fact]
        public void BarcodeValueTest()
        {
            // TODO unit test for the property 'BarcodeValue'
        }
    }
}
