/* 
 * Document AI API
 *
 * Use next-generation AI to extract data, fields, insights and text from documents. Instantly.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Cloudmersive.APIClient.NET.DocumentAI.Api;
using Cloudmersive.APIClient.NET.DocumentAI.Model;
using Cloudmersive.APIClient.NET.DocumentAI.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Cloudmersive.APIClient.NET.DocumentAI.Test
{
    /// <summary>
    ///  Class for testing ExtractedBarcodeItem
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ExtractedBarcodeItemTests
    {
        // TODO uncomment below to declare an instance variable for ExtractedBarcodeItem
        //private ExtractedBarcodeItem instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ExtractedBarcodeItem
            //instance = new ExtractedBarcodeItem();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ExtractedBarcodeItem
        /// </summary>
        [Test]
        public void ExtractedBarcodeItemInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ExtractedBarcodeItem
            //Assert.IsInstanceOfType<ExtractedBarcodeItem> (instance, "variable 'instance' is a ExtractedBarcodeItem");
        }


        /// <summary>
        /// Test the property 'BarcodeType'
        /// </summary>
        [Test]
        public void BarcodeTypeTest()
        {
            // TODO unit test for the property 'BarcodeType'
        }
        /// <summary>
        /// Test the property 'BarcodeValue'
        /// </summary>
        [Test]
        public void BarcodeValueTest()
        {
            // TODO unit test for the property 'BarcodeValue'
        }

    }

}
