/*
 * Document AI API
 *
 * Use next-generation AI to extract data, fields, insights and text from documents. Instantly.
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Cloudmersive.APIClient.NET.DocumentAI.Model;
using Cloudmersive.APIClient.NET.DocumentAI.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Cloudmersive.APIClient.NET.DocumentAI.Test.Model
{
    /// <summary>
    ///  Class for testing ExtractFieldsAndTablesResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ExtractFieldsAndTablesResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ExtractFieldsAndTablesResponse
        //private ExtractFieldsAndTablesResponse instance;

        public ExtractFieldsAndTablesResponseTests()
        {
            // TODO uncomment below to create an instance of ExtractFieldsAndTablesResponse
            //instance = new ExtractFieldsAndTablesResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ExtractFieldsAndTablesResponse
        /// </summary>
        [Fact]
        public void ExtractFieldsAndTablesResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" ExtractFieldsAndTablesResponse
            //Assert.IsType<ExtractFieldsAndTablesResponse>(instance);
        }

        /// <summary>
        /// Test the property 'Successful'
        /// </summary>
        [Fact]
        public void SuccessfulTest()
        {
            // TODO unit test for the property 'Successful'
        }

        /// <summary>
        /// Test the property 'FieldResults'
        /// </summary>
        [Fact]
        public void FieldResultsTest()
        {
            // TODO unit test for the property 'FieldResults'
        }

        /// <summary>
        /// Test the property 'TableResults'
        /// </summary>
        [Fact]
        public void TableResultsTest()
        {
            // TODO unit test for the property 'TableResults'
        }
    }
}
