/*
 * Document AI API
 *
 * Use next-generation AI to extract data, fields, insights and text from documents. Instantly.
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Cloudmersive.APIClient.NET.DocumentAI.Model;
using Cloudmersive.APIClient.NET.DocumentAI.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Cloudmersive.APIClient.NET.DocumentAI.Test.Model
{
    /// <summary>
    ///  Class for testing ExtractBarcodesAiResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ExtractBarcodesAiResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ExtractBarcodesAiResponse
        //private ExtractBarcodesAiResponse instance;

        public ExtractBarcodesAiResponseTests()
        {
            // TODO uncomment below to create an instance of ExtractBarcodesAiResponse
            //instance = new ExtractBarcodesAiResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ExtractBarcodesAiResponse
        /// </summary>
        [Fact]
        public void ExtractBarcodesAiResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" ExtractBarcodesAiResponse
            //Assert.IsType<ExtractBarcodesAiResponse>(instance);
        }

        /// <summary>
        /// Test the property 'Successful'
        /// </summary>
        [Fact]
        public void SuccessfulTest()
        {
            // TODO unit test for the property 'Successful'
        }

        /// <summary>
        /// Test the property 'BarcodeResults'
        /// </summary>
        [Fact]
        public void BarcodeResultsTest()
        {
            // TODO unit test for the property 'BarcodeResults'
        }
    }
}
