/* 
 * Document AI API
 *
 * Use next-generation AI to extract data, fields, insights and text from documents. Instantly.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Cloudmersive.APIClient.NET.DocumentAI.Api;
using Cloudmersive.APIClient.NET.DocumentAI.Model;
using Cloudmersive.APIClient.NET.DocumentAI.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Cloudmersive.APIClient.NET.DocumentAI.Test
{
    /// <summary>
    ///  Class for testing ExtractDocumentJobStatusResult
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ExtractDocumentJobStatusResultTests
    {
        // TODO uncomment below to declare an instance variable for ExtractDocumentJobStatusResult
        //private ExtractDocumentJobStatusResult instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ExtractDocumentJobStatusResult
            //instance = new ExtractDocumentJobStatusResult();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ExtractDocumentJobStatusResult
        /// </summary>
        [Test]
        public void ExtractDocumentJobStatusResultInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ExtractDocumentJobStatusResult
            //Assert.IsInstanceOfType<ExtractDocumentJobStatusResult> (instance, "variable 'instance' is a ExtractDocumentJobStatusResult");
        }


        /// <summary>
        /// Test the property 'Successful'
        /// </summary>
        [Test]
        public void SuccessfulTest()
        {
            // TODO unit test for the property 'Successful'
        }
        /// <summary>
        /// Test the property 'AsyncJobStatus'
        /// </summary>
        [Test]
        public void AsyncJobStatusTest()
        {
            // TODO unit test for the property 'AsyncJobStatus'
        }
        /// <summary>
        /// Test the property 'AsyncJobID'
        /// </summary>
        [Test]
        public void AsyncJobIDTest()
        {
            // TODO unit test for the property 'AsyncJobID'
        }
        /// <summary>
        /// Test the property 'ExtractTextResult'
        /// </summary>
        [Test]
        public void ExtractTextResultTest()
        {
            // TODO unit test for the property 'ExtractTextResult'
        }
        /// <summary>
        /// Test the property 'ExtractFieldsAndTablesResult'
        /// </summary>
        [Test]
        public void ExtractFieldsAndTablesResultTest()
        {
            // TODO unit test for the property 'ExtractFieldsAndTablesResult'
        }
        /// <summary>
        /// Test the property 'ExtractFieldsResult'
        /// </summary>
        [Test]
        public void ExtractFieldsResultTest()
        {
            // TODO unit test for the property 'ExtractFieldsResult'
        }
        /// <summary>
        /// Test the property 'ExtractClassificationResult'
        /// </summary>
        [Test]
        public void ExtractClassificationResultTest()
        {
            // TODO unit test for the property 'ExtractClassificationResult'
        }
        /// <summary>
        /// Test the property 'ErrorMessage'
        /// </summary>
        [Test]
        public void ErrorMessageTest()
        {
            // TODO unit test for the property 'ErrorMessage'
        }

    }

}
