/*
 * Document AI API
 *
 * Use next-generation AI to extract data, fields, insights and text from documents. Instantly.
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Cloudmersive.APIClient.NET.DocumentAI.Model;
using Cloudmersive.APIClient.NET.DocumentAI.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Cloudmersive.APIClient.NET.DocumentAI.Test.Model
{
    /// <summary>
    ///  Class for testing ExtractedTextPage
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ExtractedTextPageTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ExtractedTextPage
        //private ExtractedTextPage instance;

        public ExtractedTextPageTests()
        {
            // TODO uncomment below to create an instance of ExtractedTextPage
            //instance = new ExtractedTextPage();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ExtractedTextPage
        /// </summary>
        [Fact]
        public void ExtractedTextPageInstanceTest()
        {
            // TODO uncomment below to test "IsType" ExtractedTextPage
            //Assert.IsType<ExtractedTextPage>(instance);
        }

        /// <summary>
        /// Test the property 'PageNumber'
        /// </summary>
        [Fact]
        public void PageNumberTest()
        {
            // TODO unit test for the property 'PageNumber'
        }

        /// <summary>
        /// Test the property 'TextResult'
        /// </summary>
        [Fact]
        public void TextResultTest()
        {
            // TODO unit test for the property 'TextResult'
        }
    }
}
