/* 
 * Document AI API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Cloudmersive.APIClient.NET.DocumentAI.Api;
using Cloudmersive.APIClient.NET.DocumentAI.Model;
using Cloudmersive.APIClient.NET.DocumentAI.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Cloudmersive.APIClient.NET.DocumentAI.Test
{
    /// <summary>
    ///  Class for testing ExtractFieldsAndTablesResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ExtractFieldsAndTablesResponseTests
    {
        // TODO uncomment below to declare an instance variable for ExtractFieldsAndTablesResponse
        //private ExtractFieldsAndTablesResponse instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ExtractFieldsAndTablesResponse
            //instance = new ExtractFieldsAndTablesResponse();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ExtractFieldsAndTablesResponse
        /// </summary>
        [Test]
        public void ExtractFieldsAndTablesResponseInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ExtractFieldsAndTablesResponse
            //Assert.IsInstanceOfType<ExtractFieldsAndTablesResponse> (instance, "variable 'instance' is a ExtractFieldsAndTablesResponse");
        }


        /// <summary>
        /// Test the property 'Successful'
        /// </summary>
        [Test]
        public void SuccessfulTest()
        {
            // TODO unit test for the property 'Successful'
        }
        /// <summary>
        /// Test the property 'FieldResults'
        /// </summary>
        [Test]
        public void FieldResultsTest()
        {
            // TODO unit test for the property 'FieldResults'
        }
        /// <summary>
        /// Test the property 'TableResults'
        /// </summary>
        [Test]
        public void TableResultsTest()
        {
            // TODO unit test for the property 'TableResults'
        }

    }

}
