/*
 * Document AI API
 *
 * Use next-generation AI to extract data, fields, insights and text from documents. Instantly.
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Cloudmersive.APIClient.NET.DocumentAI.Model;
using Cloudmersive.APIClient.NET.DocumentAI.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Cloudmersive.APIClient.NET.DocumentAI.Test.Model
{
    /// <summary>
    ///  Class for testing ExtractDocumentJobStatusResult
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ExtractDocumentJobStatusResultTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ExtractDocumentJobStatusResult
        //private ExtractDocumentJobStatusResult instance;

        public ExtractDocumentJobStatusResultTests()
        {
            // TODO uncomment below to create an instance of ExtractDocumentJobStatusResult
            //instance = new ExtractDocumentJobStatusResult();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ExtractDocumentJobStatusResult
        /// </summary>
        [Fact]
        public void ExtractDocumentJobStatusResultInstanceTest()
        {
            // TODO uncomment below to test "IsType" ExtractDocumentJobStatusResult
            //Assert.IsType<ExtractDocumentJobStatusResult>(instance);
        }

        /// <summary>
        /// Test the property 'Successful'
        /// </summary>
        [Fact]
        public void SuccessfulTest()
        {
            // TODO unit test for the property 'Successful'
        }

        /// <summary>
        /// Test the property 'AsyncJobStatus'
        /// </summary>
        [Fact]
        public void AsyncJobStatusTest()
        {
            // TODO unit test for the property 'AsyncJobStatus'
        }

        /// <summary>
        /// Test the property 'AsyncJobID'
        /// </summary>
        [Fact]
        public void AsyncJobIDTest()
        {
            // TODO unit test for the property 'AsyncJobID'
        }

        /// <summary>
        /// Test the property 'ExtractTextResult'
        /// </summary>
        [Fact]
        public void ExtractTextResultTest()
        {
            // TODO unit test for the property 'ExtractTextResult'
        }

        /// <summary>
        /// Test the property 'ExtractFieldsAndTablesResult'
        /// </summary>
        [Fact]
        public void ExtractFieldsAndTablesResultTest()
        {
            // TODO unit test for the property 'ExtractFieldsAndTablesResult'
        }

        /// <summary>
        /// Test the property 'ExtractFieldsResult'
        /// </summary>
        [Fact]
        public void ExtractFieldsResultTest()
        {
            // TODO unit test for the property 'ExtractFieldsResult'
        }

        /// <summary>
        /// Test the property 'ExtractClassificationResult'
        /// </summary>
        [Fact]
        public void ExtractClassificationResultTest()
        {
            // TODO unit test for the property 'ExtractClassificationResult'
        }

        /// <summary>
        /// Test the property 'ErrorMessage'
        /// </summary>
        [Fact]
        public void ErrorMessageTest()
        {
            // TODO unit test for the property 'ErrorMessage'
        }
    }
}
