/* 
 * Document AI API
 *
 * Use next-generation AI to extract data, fields, insights and text from documents. Instantly.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Cloudmersive.APIClient.NET.DocumentAI.Api;
using Cloudmersive.APIClient.NET.DocumentAI.Model;
using Cloudmersive.APIClient.NET.DocumentAI.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Cloudmersive.APIClient.NET.DocumentAI.Test
{
    /// <summary>
    ///  Class for testing FieldValue
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class FieldValueTests
    {
        // TODO uncomment below to declare an instance variable for FieldValue
        //private FieldValue instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of FieldValue
            //instance = new FieldValue();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of FieldValue
        /// </summary>
        [Test]
        public void FieldValueInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" FieldValue
            //Assert.IsInstanceOfType<FieldValue> (instance, "variable 'instance' is a FieldValue");
        }


        /// <summary>
        /// Test the property 'FieldName'
        /// </summary>
        [Test]
        public void FieldNameTest()
        {
            // TODO unit test for the property 'FieldName'
        }
        /// <summary>
        /// Test the property 'FieldStringValue'
        /// </summary>
        [Test]
        public void FieldStringValueTest()
        {
            // TODO unit test for the property 'FieldStringValue'
        }

    }

}
