/*
 * Document AI API
 *
 * Use next-generation AI to extract data, fields, insights and text from documents. Instantly.
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Cloudmersive.APIClient.NET.DocumentAI.Model;
using Cloudmersive.APIClient.NET.DocumentAI.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Cloudmersive.APIClient.NET.DocumentAI.Test.Model
{
    /// <summary>
    ///  Class for testing FieldValue
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class FieldValueTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for FieldValue
        //private FieldValue instance;

        public FieldValueTests()
        {
            // TODO uncomment below to create an instance of FieldValue
            //instance = new FieldValue();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of FieldValue
        /// </summary>
        [Fact]
        public void FieldValueInstanceTest()
        {
            // TODO uncomment below to test "IsType" FieldValue
            //Assert.IsType<FieldValue>(instance);
        }

        /// <summary>
        /// Test the property 'FieldName'
        /// </summary>
        [Fact]
        public void FieldNameTest()
        {
            // TODO unit test for the property 'FieldName'
        }

        /// <summary>
        /// Test the property 'FieldStringValue'
        /// </summary>
        [Fact]
        public void FieldStringValueTest()
        {
            // TODO unit test for the property 'FieldStringValue'
        }

        /// <summary>
        /// Test the property 'AdditionalFieldStringValues'
        /// </summary>
        [Fact]
        public void AdditionalFieldStringValuesTest()
        {
            // TODO unit test for the property 'AdditionalFieldStringValues'
        }
    }
}
