/* 
 * Document AI API
 *
 * Use next-generation AI to extract data, fields, insights and text from documents. Instantly.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Cloudmersive.APIClient.NET.DocumentAI.Api;
using Cloudmersive.APIClient.NET.DocumentAI.Model;
using Cloudmersive.APIClient.NET.DocumentAI.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Cloudmersive.APIClient.NET.DocumentAI.Test
{
    /// <summary>
    ///  Class for testing FieldToExtract
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class FieldToExtractTests
    {
        // TODO uncomment below to declare an instance variable for FieldToExtract
        //private FieldToExtract instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of FieldToExtract
            //instance = new FieldToExtract();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of FieldToExtract
        /// </summary>
        [Test]
        public void FieldToExtractInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" FieldToExtract
            //Assert.IsInstanceOfType<FieldToExtract> (instance, "variable 'instance' is a FieldToExtract");
        }


        /// <summary>
        /// Test the property 'FieldName'
        /// </summary>
        [Test]
        public void FieldNameTest()
        {
            // TODO unit test for the property 'FieldName'
        }
        /// <summary>
        /// Test the property 'FieldOptional'
        /// </summary>
        [Test]
        public void FieldOptionalTest()
        {
            // TODO unit test for the property 'FieldOptional'
        }
        /// <summary>
        /// Test the property 'FieldDescription'
        /// </summary>
        [Test]
        public void FieldDescriptionTest()
        {
            // TODO unit test for the property 'FieldDescription'
        }
        /// <summary>
        /// Test the property 'FieldExample'
        /// </summary>
        [Test]
        public void FieldExampleTest()
        {
            // TODO unit test for the property 'FieldExample'
        }

    }

}
