/* 
 * Document AI API
 *
 * Use next-generation AI to extract data, fields, insights and text from documents. Instantly.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Cloudmersive.APIClient.NET.DocumentAI.Api;
using Cloudmersive.APIClient.NET.DocumentAI.Model;
using Cloudmersive.APIClient.NET.DocumentAI.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Cloudmersive.APIClient.NET.DocumentAI.Test
{
    /// <summary>
    ///  Class for testing PolicyRuleViolation
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class PolicyRuleViolationTests
    {
        // TODO uncomment below to declare an instance variable for PolicyRuleViolation
        //private PolicyRuleViolation instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of PolicyRuleViolation
            //instance = new PolicyRuleViolation();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of PolicyRuleViolation
        /// </summary>
        [Test]
        public void PolicyRuleViolationInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" PolicyRuleViolation
            //Assert.IsInstanceOfType<PolicyRuleViolation> (instance, "variable 'instance' is a PolicyRuleViolation");
        }


        /// <summary>
        /// Test the property 'RuleId'
        /// </summary>
        [Test]
        public void RuleIdTest()
        {
            // TODO unit test for the property 'RuleId'
        }
        /// <summary>
        /// Test the property 'RuleViolationRiskScore'
        /// </summary>
        [Test]
        public void RuleViolationRiskScoreTest()
        {
            // TODO unit test for the property 'RuleViolationRiskScore'
        }
        /// <summary>
        /// Test the property 'RuleViolationRationale'
        /// </summary>
        [Test]
        public void RuleViolationRationaleTest()
        {
            // TODO unit test for the property 'RuleViolationRationale'
        }

    }

}
