/* 
 * Document AI API
 *
 * Use next-generation AI to extract data, fields, insights and text from documents. Instantly.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Cloudmersive.APIClient.NET.DocumentAI.Api;
using Cloudmersive.APIClient.NET.DocumentAI.Model;
using Cloudmersive.APIClient.NET.DocumentAI.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Cloudmersive.APIClient.NET.DocumentAI.Test
{
    /// <summary>
    ///  Class for testing PolicyRule
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class PolicyRuleTests
    {
        // TODO uncomment below to declare an instance variable for PolicyRule
        //private PolicyRule instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of PolicyRule
            //instance = new PolicyRule();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of PolicyRule
        /// </summary>
        [Test]
        public void PolicyRuleInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" PolicyRule
            //Assert.IsInstanceOfType<PolicyRule> (instance, "variable 'instance' is a PolicyRule");
        }


        /// <summary>
        /// Test the property 'RuleId'
        /// </summary>
        [Test]
        public void RuleIdTest()
        {
            // TODO unit test for the property 'RuleId'
        }
        /// <summary>
        /// Test the property 'RuleType'
        /// </summary>
        [Test]
        public void RuleTypeTest()
        {
            // TODO unit test for the property 'RuleType'
        }
        /// <summary>
        /// Test the property 'RuleDescription'
        /// </summary>
        [Test]
        public void RuleDescriptionTest()
        {
            // TODO unit test for the property 'RuleDescription'
        }

    }

}
