/* 
 * Document AI API
 *
 * Use next-generation AI to extract data, fields, insights and text from documents. Instantly.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Cloudmersive.APIClient.NET.DocumentAI.Api;
using Cloudmersive.APIClient.NET.DocumentAI.Model;
using Cloudmersive.APIClient.NET.DocumentAI.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Cloudmersive.APIClient.NET.DocumentAI.Test
{
    /// <summary>
    ///  Class for testing SummarizeDocumentResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class SummarizeDocumentResponseTests
    {
        // TODO uncomment below to declare an instance variable for SummarizeDocumentResponse
        //private SummarizeDocumentResponse instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of SummarizeDocumentResponse
            //instance = new SummarizeDocumentResponse();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of SummarizeDocumentResponse
        /// </summary>
        [Test]
        public void SummarizeDocumentResponseInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" SummarizeDocumentResponse
            //Assert.IsInstanceOfType<SummarizeDocumentResponse> (instance, "variable 'instance' is a SummarizeDocumentResponse");
        }


        /// <summary>
        /// Test the property 'Successful'
        /// </summary>
        [Test]
        public void SuccessfulTest()
        {
            // TODO unit test for the property 'Successful'
        }
        /// <summary>
        /// Test the property 'DocumentSummaryText'
        /// </summary>
        [Test]
        public void DocumentSummaryTextTest()
        {
            // TODO unit test for the property 'DocumentSummaryText'
        }

    }

}
