/*
 * Document AI API
 *
 * Use next-generation AI to extract data, fields, insights and text from documents. Instantly.
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Cloudmersive.APIClient.NET.DocumentAI.Model;
using Cloudmersive.APIClient.NET.DocumentAI.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Cloudmersive.APIClient.NET.DocumentAI.Test.Model
{
    /// <summary>
    ///  Class for testing TableResultRow
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class TableResultRowTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for TableResultRow
        //private TableResultRow instance;

        public TableResultRowTests()
        {
            // TODO uncomment below to create an instance of TableResultRow
            //instance = new TableResultRow();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of TableResultRow
        /// </summary>
        [Fact]
        public void TableResultRowInstanceTest()
        {
            // TODO uncomment below to test "IsType" TableResultRow
            //Assert.IsType<TableResultRow>(instance);
        }

        /// <summary>
        /// Test the property 'Cells'
        /// </summary>
        [Fact]
        public void CellsTest()
        {
            // TODO unit test for the property 'Cells'
        }
    }
}
