/* 
 * Document AI API
 *
 * Use next-generation AI to extract data, fields, insights and text from documents. Instantly.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Cloudmersive.APIClient.NET.DocumentAI.Api;
using Cloudmersive.APIClient.NET.DocumentAI.Model;
using Cloudmersive.APIClient.NET.DocumentAI.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Cloudmersive.APIClient.NET.DocumentAI.Test
{
    /// <summary>
    ///  Class for testing TableResultCell
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class TableResultCellTests
    {
        // TODO uncomment below to declare an instance variable for TableResultCell
        //private TableResultCell instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of TableResultCell
            //instance = new TableResultCell();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of TableResultCell
        /// </summary>
        [Test]
        public void TableResultCellInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" TableResultCell
            //Assert.IsInstanceOfType<TableResultCell> (instance, "variable 'instance' is a TableResultCell");
        }


        /// <summary>
        /// Test the property 'CellHeader'
        /// </summary>
        [Test]
        public void CellHeaderTest()
        {
            // TODO unit test for the property 'CellHeader'
        }
        /// <summary>
        /// Test the property 'CellValue'
        /// </summary>
        [Test]
        public void CellValueTest()
        {
            // TODO unit test for the property 'CellValue'
        }

    }

}
