/*
 * Document AI API
 *
 * Use next-generation AI to extract data, fields, insights and text from documents. Instantly.
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Cloudmersive.APIClient.NET.DocumentAI.Model;
using Cloudmersive.APIClient.NET.DocumentAI.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Cloudmersive.APIClient.NET.DocumentAI.Test.Model
{
    /// <summary>
    ///  Class for testing TableResultCell
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class TableResultCellTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for TableResultCell
        //private TableResultCell instance;

        public TableResultCellTests()
        {
            // TODO uncomment below to create an instance of TableResultCell
            //instance = new TableResultCell();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of TableResultCell
        /// </summary>
        [Fact]
        public void TableResultCellInstanceTest()
        {
            // TODO uncomment below to test "IsType" TableResultCell
            //Assert.IsType<TableResultCell>(instance);
        }

        /// <summary>
        /// Test the property 'CellHeader'
        /// </summary>
        [Fact]
        public void CellHeaderTest()
        {
            // TODO unit test for the property 'CellHeader'
        }

        /// <summary>
        /// Test the property 'CellValue'
        /// </summary>
        [Fact]
        public void CellValueTest()
        {
            // TODO unit test for the property 'CellValue'
        }
    }
}
