/*
 * Document AI API
 *
 * Use next-generation AI to extract data, fields, insights and text from documents. Instantly.
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Cloudmersive.APIClient.NET.DocumentAI.Model;
using Cloudmersive.APIClient.NET.DocumentAI.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Cloudmersive.APIClient.NET.DocumentAI.Test.Model
{
    /// <summary>
    ///  Class for testing TableResult
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class TableResultTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for TableResult
        //private TableResult instance;

        public TableResultTests()
        {
            // TODO uncomment below to create an instance of TableResult
            //instance = new TableResult();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of TableResult
        /// </summary>
        [Fact]
        public void TableResultInstanceTest()
        {
            // TODO uncomment below to test "IsType" TableResult
            //Assert.IsType<TableResult>(instance);
        }

        /// <summary>
        /// Test the property 'Title'
        /// </summary>
        [Fact]
        public void TitleTest()
        {
            // TODO unit test for the property 'Title'
        }

        /// <summary>
        /// Test the property 'Rows'
        /// </summary>
        [Fact]
        public void RowsTest()
        {
            // TODO unit test for the property 'Rows'
        }
    }
}
