/* 
 * Document AI API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Cloudmersive.APIClient.NET.DocumentAI.Api;
using Cloudmersive.APIClient.NET.DocumentAI.Model;
using Cloudmersive.APIClient.NET.DocumentAI.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Cloudmersive.APIClient.NET.DocumentAI.Test
{
    /// <summary>
    ///  Class for testing TableResultRow
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class TableResultRowTests
    {
        // TODO uncomment below to declare an instance variable for TableResultRow
        //private TableResultRow instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of TableResultRow
            //instance = new TableResultRow();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of TableResultRow
        /// </summary>
        [Test]
        public void TableResultRowInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" TableResultRow
            //Assert.IsInstanceOfType<TableResultRow> (instance, "variable 'instance' is a TableResultRow");
        }


        /// <summary>
        /// Test the property 'Cells'
        /// </summary>
        [Test]
        public void CellsTest()
        {
            // TODO unit test for the property 'Cells'
        }

    }

}
